version: '3'
 
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 6603:3306
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      # MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: